# Generated by Django 4.1.3 on 2023-03-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.CharField(max_length=200)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='frontend.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('creatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.utente')),
            ],
        ),
    ]
