# Generated by Django 4.1.3 on 2023-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_utente_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
