# Generated by Django 4.1.7 on 2023-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='password',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
