# Generated by Django 4.1.7 on 2023-03-27 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_utente_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dataPubblicazione',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 7, 56, 33, 155715, tzinfo=datetime.timezone.utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
