# Generated by Django 4.1.7 on 2023-03-28 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_post_datapubblicazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dataPubblicazione']},
        ),
        migrations.AlterField(
            model_name='post',
            name='dataPubblicazione',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 10, 59, 55, 916110, tzinfo=datetime.timezone.utc)),
        ),
    ]
