# Generated by Django 4.1.3 on 2023-03-29 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_post_options_alter_post_datapubblicazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dataPubblicazione',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 15, 17, 1, 883806, tzinfo=datetime.timezone.utc)),
        ),
    ]
