# Generated by Django 4.1.7 on 2023-04-03 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_post_datapubblicazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descrizione',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='dataPubblicazione',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 10, 58, 12, 331638, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
