# Generated by Django 4.1.7 on 2023-04-03 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_post_descrizione_alter_post_datapubblicazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dataPubblicazione',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 10, 58, 30, 526710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(upload_to=''),
        ),
    ]
