# Generated by Django 4.1.7 on 2023-04-03 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_alter_post_datapubblicazione_alter_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dataPubblicazione',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 14, 29, 13, 893279, tzinfo=datetime.timezone.utc)),
        ),
    ]
